name: release

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  BINARY_NAME: image-syncer

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2

      - uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: "${{ env.BINARY_NAME }}"
          build_flags: -v